### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by guigui0246** [polskoniemiec/console-discord#1]
![Image of installation fail](https://github.com/polskoniemiec/console-discord/assets/86032032/01c54d2f-9831-4170-8f66-0d0dd65d0309)
You can't install using the command given in requirement after installing node
If you run the app without it does nothing (not even an error or a warning)
How do I fix it ?
There is no installation error on node's side : 
![Image of node installation success and then test of the app](https://github.com/polskoniemiec/console-discord/assets/86032032/0f35b14d-c5b0-47d8-b6f3-2369cd9cde32)

**Comment by polskoniemiec** [comment]
it seems you dont have node, [download link](https://nodejs.org/en), or use your package manager

**Comment by guigui0246** [comment]
![image](https://github.com/polskoniemiec/console-discord/assets/86032032/a1004faf-1acb-47b8-b865-341077266214)
It says it's installed

**Comment by polskoniemiec** [comment]
remove line 219 so it doesnt clear the screen then try running `node index.js` and tell me that errors are there

**Comment by guigui0246** [comment]
Node doesn't give any errors and npm (even without arguments) give this error:
```
error while loading shared libraries: ?: cannot open shared object file: No such file or directory
Could not determine Node.js install directory
```

**Comment by polskoniemiec** [comment]
this looks like a badly installed node/npm
run `node -v` and `npm list` and tell me the versions of both programs
i also found this, but thats on windows so idk if it will help you https://stackoverflow.com/questions/67559611/error-could-not-determine-node-js-install-directory

**Comment by guigui0246** [comment]
Le lundi 18 septembre 2023 à 13:49:40 UTC+2, Olie ***@***.***> a écrit :  
 
 


this looks like a badly installed node/npm
run node -v and npm list and tell me the versions of both programs
i also found this, but thats on windows so idk if it will help you https://stackoverflow.com/questions/67559611/error-could-not-determine-node-js-install-directory

**Comment by guigui0246** [comment]
didn't work through email

**Comment by guigui0246** [comment]
I think I should give the error I have when not using bash :
```Error [INVALID_INTENTS]: [Bot Token] Invalid intent provided for WebSocket intents.
    at WebSocketManager.createShards (C:\Users\guigui0246-EPITECH\OneDrive\kerfus-bot\kerfus-bot-but-in-python\test\console-discord\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketManager.js:265:15)
    at async Client.login (C:\Users\guigui0246-EPITECH\OneDrive\kerfus-bot\kerfus-bot-but-in-python\test\console-discord\node_modules\discord.js-selfbot-v13\src\client\Client.js:342:7) {
  [Symbol(code)]: 'INVALID_INTENTS'
}```

**Comment by polskoniemiec** [comment]
> ![image](https://user-images.githubusercontent.com/86032032/268663989-ce0d4cdc-66e3-48cc-a500-dcc67e69ec70.png)

this looks like a badly installed node, `node -v` would print the version of node


also r u logging into a user account or a bot account?

**Comment by guigui0246** [comment]
I'm logging using a bot token

**Comment by guigui0246** [comment]
Using bash to execute directly windows Node doesn't work either. 
![image](https://github.com/polskoniemiec/console-discord/assets/86032032/376817e0-a848-4f93-badf-892de2577f0d)

**Comment by polskoniemiec** [comment]
this is for user accounts only, theoretically i could add support for bot accounts but it will take a bit (older versions used bot accounts, you can clone one of those to use a bot acc)

**Comment by polskoniemiec** [comment]
i created a bot branch in case you want to use that

**Comment by guigui0246** [comment]
On the bot branch I get :
Error: Used disallowed intents

ChatGPT said that in Privileged Gateway Intents in the portal I don't have the same intents as in the code

**Comment by guigui0246** [comment]
Now works after enabling the all

**Comment by guigui0246** [comment]
You still should make it so installation says you need to enable all of Privileged Gateway Intents at least. Or your code tries all intents combination
